### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

### ISSUE THREAD

**Issue by Algabri** [hnuzhy/DirectMHP#12]
Hello, Hnuzhy

When running code `compare_error_analysis_v2.py`

I got this error:

```
Traceback (most recent call last):
  File "/home/redhwan/2/HPE/DirectMHP/exps/compare_error_analysis_v2.py", line 269, in <module>
    main(args)
  File "/home/redhwan/2/HPE/DirectMHP/exps/compare_error_analysis_v2.py", line 108, in main
    pd_results_list = json.load(json_f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
```

My parser is:

```
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='3DDFA inference pipeline')
    
    parser.add_argument('--root-imgdir', default='/home/redhwan/2/HPE/DirectMHP/exps/AGORA/HPE/images/validation',
                        help='root path to multiple images')
    parser.add_argument('--json-file', default='/home/redhwan/2/HPE/DirectMHP/runs/DirectMHP/agora_m_1280_e300_t40_lw010/weights/best.pt',
                        help='json file path that contains multiple images and their head bboxes')
    parser.add_argument('--anno-file', default='/home/redhwan/2/HPE/DirectMHP/exps/AGORA/HPE/annotations/coco_style_validation.json',
                        help='json file path that contains ground-truths of validation set')
    parser.add_argument('-m', '--mode', default='cpu', type=str, help='gpu or cpu mode')
    parser.add_argument('--debug',  action='store_true', help='whether set into debug mode')
    
    args = parser.parse_args()
    main(args)
```
Your explanation is :
you used `/datasdc/zhouhuayi/face_related/DirectMHP/runs/DirectMHP/agora_m_1280_e300_t40_lw010/weights/val_best_c0.001_i0.65_pd_full.json`

How did you get this --json-file?

Thank you so much in advance?

**Comment by hnuzhy** [comment]
This file is for MAE error plotting. `--json-file` should be your predicted results in json format, not a `best.pt` weight file. It seems that you do not understand the code very well. You can get results file like `val_best_c0.001_i0.65_pd_full.json` by running `python val.py` for error analysis.

**Comment by Algabri** [comment]
Oh, I see.
Thank you soooooo much.
